// Export all schemas
export * from './users';
export * from './permissions';
export * from './leaves';
export * from './salary';
export * from './facilities';
export * from './medical';
export * from './consultant';
export * from './vendors';
export * from './vouchers';
export * from './audit';
export * from './employeeEducation';
export * from './employeeWorkHistory';
export * from './profileChangeRequests';
export * from './notifications';
export * from './attachments';
